### ISSUE TITLE
map not showing up on mobile 

### ISSUE THREAD

**Issue by TomAtlas** [ChaseMilligan/CannaMap#11]
Describe the bug
Site pop up menu not showing up in horizontal mode (using safari on an iphone 10)

To Reproduce

Go to '...' canna-map.ca website ion mobile
Click on '....' delivery in pop up menu
See error ...map is blank
Expected behavior
map shows up similar to desktop site 

Screenshots

Desktop (please complete the following information):

![image1](https://user-images.githubusercontent.com/70860696/92337388-45bcd880-f077-11ea-9e0d-5917a7ff428f.png)

Smartphone (please complete the following information):

Device: 10
OS: iOS 13.6.1
Browser safari
Version iOS 13.6.1

**Comment by ChaseMilligan** [comment]
This is happening becasue you have loaction disabled on the website or in your settings for your browser. I can add an error message prompting the user to enable that setting or something.
