### ISSUE TITLE
Location Search Bar

### ISSUE THREAD

**Issue by TomAtlas** [ChaseMilligan/CannaMap#12]
**Is your feature request related to a problem? Please describe.**
Search bar to determine user location for website use on delivieries and featured pages

**Describe the solution you'd like**
please add a Search bar to determine user location for website use on delivieries and featured pages

**Additional context**
including a screenshot of the general idea I like that he has the featured deliveries at the top followed by top rated and then
all deliveries if there is any way to replicate this style it would be perfect

![1](https://user-images.githubusercontent.com/70860696/92337663-33dc3500-f079-11ea-90dd-9e6ff4e3d6c0.jpg)

**Comment by ChaseMilligan** [comment]
Currently I am already getting the user's location based on their devices location. Is there a need for them to type it in?

**Comment by TomAtlas** [comment]
it is important to have in there because some users might prefer not to allow location services so they get no map at all and also incase you are getting your delivery to a different location than where you currently are it would be useful to determine suitable deliveries based on search instead of only having it based off of current location

**Comment by ChaseMilligan** [comment]
For sure. Ill brainstorm some ways to add this in.
